### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by KrystianLi** [shadow1ng/fscan#163]
在 ./fscan_amd64 -uf ./urls.txt -np -o ./urls_result.txt -t 100    执行过程中会出现如下错误，这样该如何解决
```
fatal error: concurrent map writes

goroutine 4283 [running]:
runtime.throw({0xc64420, 0x4d4b65})
        runtime/panic.go:1198 +0x71 fp=0xc003a27538 sp=0xc003a27508 pc=0x433511
runtime.mapassign_faststr(0xc001aa42a0, 0xc52f70, {0xc001e4fc90, 0xc})
        runtime/map_faststr.go:211 +0x39c fp=0xc003a275a0 sp=0xc003a27538 pc=0x412a1c
github.com/shadow1ng/fscan/WebScan/lib.executePoc.func1({{0xc001e4fc30, 0x4}, {0xc001aa4270, 0x2f}, 0xc0023467e0, {0xc0015feea0, 0x5b}, {0x0, 0x0}, 0x1, ...})
        github.com/shadow1ng/fscan/WebScan/lib/check.go:176 +0xaef fp=0xc003a27878 sp=0xc003a275a0 pc=0xa75b2f
github.com/shadow1ng/fscan/WebScan/lib.executePoc.func2({0xc001ed1560, 0x1, 0xc57145})
        github.com/shadow1ng/fscan/WebScan/lib/check.go:230 +0xb5 fp=0xc003a27960 sp=0xc003a27878 pc=0xa74fd5
github.com/shadow1ng/fscan/WebScan/lib.executePoc(0xc006299500, 0xc0025c1710)
        github.com/shadow1ng/fscan/WebScan/lib/check.go:245 +0xb25 fp=0xc003a27f38 sp=0xc003a27960 pc=0xa74245
github.com/shadow1ng/fscan/WebScan/lib.CheckMultiPoc.func1()
        github.com/shadow1ng/fscan/WebScan/lib/check.go:34 +0x8c fp=0xc003a27fe0 sp=0xc003a27f38 pc=0xa7362c
runtime.goexit()
        runtime/asm_amd64.s:1581 +0x1 fp=0xc003a27fe8 sp=0xc003a27fe0 pc=0x462c61
created by github.com/shadow1ng/fscan/WebScan/lib.CheckMultiPoc
        github.com/shadow1ng/fscan/WebScan/lib/check.go:32 +0x5e

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc0004edb58)
        runtime/sema.go:56 +0x25
sync.(*WaitGroup).Wait(0x0)
        sync/waitgroup.go:130 +0x71
github.com/shadow1ng/fscan/Plugins.Scan({{0x0, 0x0}, {0xc000172480, 0x45c}, {0x0, 0x0}, {0xc000457830, 0x15}, {0x0, 0x0}, ...})
        github.com/shadow1ng/fscan/Plugins/scanner.go:85 +0x505
main.main()
        github.com/shadow1ng/fscan/main.go:15 +0x98

goroutine 6 [chan receive]:
github.com/shadow1ng/fscan/common.SaveLog()
        github.com/shadow1ng/fscan/common/log.go:32 +0x54
created by github.com/shadow1ng/fscan/common.init.0
        github.com/shadow1ng/fscan/common/log.go:22 +0x25

goroutine 7 [chan send]:
github.com/shadow1ng/fscan/WebScan/lib.CheckMultiPoc(0xc01f169e00, {0xc000efd000, 0x169, 0xa}, 0x14)
        github.com/shadow1ng/fscan/WebScan/lib/check.go:49 +0x10f
github.com/shadow1ng/fscan/WebScan.Execute({0x14, 0x0, 0x5, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0xc016da9c60, ...}, ...})
        github.com/shadow1ng/fscan/WebScan/WebScan.go:48 +0x2d8
github.com/shadow1ng/fscan/WebScan.WebScan(0xc000138700)
        github.com/shadow1ng/fscan/WebScan/WebScan.go:31 +0x1b8
github.com/shadow1ng/fscan/Plugins.WebTitle(0xc000138700)
        github.com/shadow1ng/fscan/Plugins/webtitle.go:26 +0x145
reflect.Value.call({0xb44a40, 0xeeaa98, 0x13}, {0xc534cf, 0x4}, {0xc000500018, 0x1, 0x1})
        reflect/value.go:543 +0x814
reflect.Value.Call({0xb44a40, 0xeeaa98, 0xc562dc}, {0xc000500018, 0x1, 0x1})
        reflect/value.go:339 +0xc5
github.com/shadow1ng/fscan/Plugins.ScanFunc(0x0, {0xc562dc, 0x0}, {0xc000056fc0, 0x1, 0x0})
        github.com/shadow1ng/fscan/Plugins/scanner.go:120 +0x1d4
github.com/shadow1ng/fscan/Plugins.AddScan.func1()
        github.com/shadow1ng/fscan/Plugins/scanner.go:99 +0xf4
created by github.com/shadow1ng/fscan/Plugins.AddScan
        github.com/shadow1ng/fscan/Plugins/scanner.go:95 +0x145

goroutine 22161 [select]:
net/http.(*Transport).getConn(0xc000147a40, 0xc0148a2400, {{}, 0x0, {0xc014391d10, 0x5}, {0xc00773cf90, 0x11}, 0x0})
        net/http/transport.go:1372 +0x5d2
net/http.(*Transport).roundTrip(0xc000147a40, 0xc0067d4d00)
        net/http/transport.go:581 +0x774
net/http.(*Transport).RoundTrip(0xc0067d4d00, 0xfab0c0)
        net/http/roundtrip.go:18 +0x19
net/http.send(0xc0067d4800, {0xfab0c0, 0xc000147a40}, {0xc2f020, 0x4b5f01, 0x196fae0})
        net/http/client.go:252 +0x5d8
net/http.(*Client).send(0xc0003f4a50, 0xc0067d4800, {0xc010626820, 0xc01054d358, 0x196fae0})
        net/http/client.go:176 +0x9b
net/http.(*Client).do(0xc0003f4a50, 0xc0067d4800)
        net/http/client.go:725 +0x908
net/http.(*Client).Do(...)
        net/http/client.go:593
github.com/shadow1ng/fscan/WebScan/lib.DoRequest(0xc0067d4800, 0x0)
        github.com/shadow1ng/fscan/WebScan/lib/eval.go:508 +0x250
github.com/shadow1ng/fscan/WebScan/lib.executePoc.func1({{0xc0021d4898, 0x4}, {0xc002766780, 0x15}, 0x0, {0xc010189b80, 0x36}, {0x0, 0x0}, 0x0, ...})
        github.com/shadow1ng/fscan/WebScan/lib/check.go:197 +0x79a
github.com/shadow1ng/fscan/WebScan/lib.executePoc.func2({0xc00126da40, 0x1, 0xc57145})
        github.com/shadow1ng/fscan/WebScan/lib/check.go:230 +0xb5
github.com/shadow1ng/fscan/WebScan/lib.executePoc(0xc005c0e000, 0xc0022fc240)
        github.com/shadow1ng/fscan/WebScan/lib/check.go:245 +0xb25
github.com/shadow1ng/fscan/WebScan/lib.CheckMultiPoc.func1()
        github.com/shadow1ng/fscan/WebScan/lib/check.go:34 +0x8c
created by github.com/shadow1ng/fscan/WebScan/lib.CheckMultiPoc
        github.com/shadow1ng/fscan/WebScan/lib/check.go:32 +0x5e

goroutine 22699 [select]:
net/http.(*Transport).getConn(0xc000147a40, 0xc030378c00, {{}, 0x0, {0xc0120e6500, 0x5}, {0xc032e51488, 0x11}, 0x0})
        net/http/transport.go:1372 +0x5d2
net/http.(*Transport).roundTrip(0xc000147a40, 0xc00b4f2500)
        net/http/transport.go:581 +0x774
net/http.(*Transport).RoundTrip(0xc00b4f2500, 0xfab0c0)
        net/http/roundtrip.go:18 +0x19
net/http.send(0xc00b4f2400, {0xfab0c0, 0xc000147a40}, {0xc2f020, 0x4b5f01, 0x196fae0})
        net/http/client.go:252 +0x5d8
net/http.(*Client).send(0xc0003f4a50, 0xc00b4f2400, {0xc01f6fb930, 0x4, 0x196fae0})
        net/http/client.go:176 +0x9b
net/http.(*Client).do(0xc0003f4a50, 0xc00b4f2400)
        net/http/client.go:725 +0x908
net/http.(*Client).Do(...)
        net/http/client.go:593
github.com/shadow1ng/fscan/WebScan/lib.DoRequest(0xc00b4f2400, 0x0)
        github.com/shadow1ng/fscan/WebScan/lib/eval.go:508 +0x250
github.com/shadow1ng/fscan/WebScan/lib.executePoc.func1({{0xc0024ad788, 0x4}, {0xc001590070, 0x63}, 0xc00226dbf0, {0xc00230d180, 0x62}, {0xc0024a7ec0, 0x31}, 0x0, ...})
        github.com/shadow1ng/fscan/WebScan/lib/check.go:197 +0x79a
github.com/shadow1ng/fscan/WebScan/lib.executePoc.func2({0xc0026fecc0, 0x2, 0xc57145})
        github.com/shadow1ng/fscan/WebScan/lib/check.go:230 +0xb5
github.com/shadow1ng/fscan/WebScan/lib.executePoc(0xc003dbc600, 0xc0024a3680)
        github.com/shadow1ng/fscan/WebScan/lib/check.go:248 +0xbca
github.com/shadow1ng/fscan/WebScan/lib.CheckMultiPoc.func1()
        github.com/shadow1ng/fscan/WebScan/lib/check.go:34 +0x8c
created by github.com/shadow1ng/fscan/WebScan/lib.CheckMultiPoc
        github.com/shadow1ng/fscan/WebScan/lib/check.go:32 +0x5e

goroutine 17212 [select]:
net/http.(*Transport).getConn(0xc000147a40, 0xc02c878fc0, {{}, 0x0, {0xc02a640870, 0x5}, {0xc02b25e690, 0x11}, 0x0})
        net/http/transport.go:1372 +0x5d2
net/http.(*Transport).roundTrip(0xc000147a40, 0xc01f020600)
        net/http/transport.go:581 +0x774
net/http.(*Transport).RoundTrip(0xc01f020600, 0xfab0c0)
        net/http/roundtrip.go:18 +0x19
net/http.send(0xc01f020400, {0xfab0c0, 0xc000147a40}, {0xc2f020, 0x4b5f01, 0x196fae0})
        net/http/client.go:252 +0x5d8
net/http.(*Client).send(0xc0003f4a50, 0xc01f020400, {0xc01c1591e0, 0x7c, 0x196fae0})
        net/http/client.go:176 +0x9b
net/http.(*Client).do(0xc0003f4a50, 0xc01f020400)
        net/http/client.go:725 +0x908
net/http.(*Client).Do(...)
        net/http/client.go:593
github.com/shadow1ng/fscan/WebScan/lib.DoRequest(0xc01c76e930, 0x0)
        github.com/shadow1ng/fscan/WebScan/lib/eval.go:508 +0x250
github.com/shadow1ng/fscan/WebScan/lib.executePoc.func1({{0xc0015e3686, 0x3}, {0xc001ba0380, 0x73}, 0x0, {0x0, 0x0}, {0x0, 0x0}, 0x0, ...})
        github.com/shadow1ng/fscan/WebScan/lib/check.go:197 +0x79a
github.com/shadow1ng/fscan/WebScan/lib.executePoc.func2({0xc0010ab140, 0x1, 0xc57145})
        github.com/shadow1ng/fscan/WebScan/lib/check.go:230 +0xb5
github.com/shadow1ng/fscan/WebScan/lib.executePoc(0xc0021de300, 0xc00250d3b0)
        github.com/shadow1ng/fscan/WebScan/lib/check.go:245 +0xb25
github.com/shadow1ng/fscan/WebScan/lib.CheckMultiPoc.func1()
        github.com/shadow1ng/fscan/WebScan/lib/check.go:34 +0x8c
created by github.com/shadow1ng/fscan/WebScan/lib.CheckMultiPoc
        github.com/shadow1ng/fscan/WebScan/lib/check.go:32 +0x5e

goroutine 71782 [IO wait]:
internal/poll.runtime_pollWait(0x7fd98d0ba700, 0x77)
        runtime/netpoll.go:229 +0x89
internal/poll.(*pollDesc).wait(0xc029bd4680, 0xc016a24c90, 0x0)
        internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitWrite(...)
        internal/poll/fd_poll_runtime.go:93
internal/poll.(*FD).WaitWrite(...)
        internal/poll/fd_unix.go:529
net.(*netFD).connect(0xc029bd4680, {0xfbc8a8, 0xc02b149560}, {0xc021c0f428, 0x40cc14}, {0xfab440, 0xc02b135760})
        net/fd_unix.go:142 +0x717
net.(*netFD).dial(0xc029bd4680, {0xfbc8a8, 0xc02b149560}, {0xfc2108, 0x0}, {0xfc2108, 0xc016a24c60}, 0xc021c0f618)
        net/sock_posix.go:150 +0x379
net.socket({0xfbc8a8, 0xc02b149560}, {0xc532f3, 0x3}, 0x2, 0x1, 0x0, 0x18, {0xfc2108, 0x0}, ...)
        net/sock_posix.go:71 +0x2a5
net.internetSocket({0xfbc8a8, 0xc02b149560}, {0xc532f3, 0x3}, {0xfc2108, 0x0}, {0xfc2108, 0xc016a24c60}, 0xc01849fe80, 0x0, ...)
        net/ipsock_posix.go:142 +0xf8
net.(*sysDialer).doDialTCP(0xc029bd4600, {0xfbc8a8, 0xc02b149560}, 0x0, 0xb71600)
        net/tcpsock_posix.go:66 +0xa5
net.(*sysDialer).dialTCP(0xc02b149560, {0xfbc8a8, 0xc02b149560}, 0xc000058800, 0xc024f82400)
        net/tcpsock_posix.go:62 +0x59
net.(*sysDialer).dialSingle(0xc029bd4600, {0xfbc8a8, 0xc02b149560}, {0xfb4f58, 0xc016a24c60})
        net/dial.go:583 +0x28b
net.(*sysDialer).dialSerial(0xc029bd4600, {0xfbc8a8, 0xc02b149560}, {0xc023c7b4b0, 0x1, 0xc53883})
        net/dial.go:551 +0x312
net.(*Dialer).DialContext(0xc000031140, {0xfbc8a8, 0xc02b149560}, {0xc532f3, 0x7fd98d18ae08}, {0xc02aaa9080, 0x118})
        net/dial.go:428 +0x736
net/http.(*Transport).dial(0xc02b149560, {0xfbc8a8, 0xc02b149560}, {0xc532f3, 0x1}, {0xc02aaa9080, 0xfb32e8})
        net/http/transport.go:1166 +0xda
net/http.(*Transport).dialConn(0xc000147a40, {0xfbc8a8, 0xc02b149560}, {{}, 0x0, {0xc01c74b3e0, 0x4}, {0xc02aaa9080, 0x10}, 0x0})
        net/http/transport.go:1604 +0x845
net/http.(*Transport).dialConnFor(0xfab5c0, 0xc0263291e0)
        net/http/transport.go:1446 +0xb0
created by net/http.(*Transport).decConnsPerHost
        net/http/transport.go:1484 +0x418

goroutine 16412 [select]:
net/http.(*Transport).getConn(0xc000147a40, 0xc0212db280, {{}, 0x0, {0xc020757900, 0x4}, {0xc017730e80, 0x20}, 0x0})
        net/http/transport.go:1372 +0x5d2
net/http.(*Transport).roundTrip(0xc000147a40, 0xc0203f8800)
        net/http/transport.go:581 +0x774
net/http.(*Transport).RoundTrip(0xc0203f8800, 0xfab0c0)
        net/http/roundtrip.go:18 +0x19
net/http.send(0xc0203f8700, {0xfab0c0, 0xc000147a40}, {0xc2f020, 0x4b5f01, 0x196fae0})
        net/http/client.go:252 +0x5d8
net/http.(*Client).send(0xc0003f4a50, 0xc0203f8700, {0xc01f6fb930, 0x0, 0x196fae0})
        net/http/client.go:176 +0x9b
net/http.(*Client).do(0xc0003f4a50, 0xc0203f8700)
        net/http/client.go:725 +0x908
net/http.(*Client).Do(...)
        net/http/client.go:593
github.com/shadow1ng/fscan/WebScan/lib.DoRequest(0xc00a26ed80, 0x0)
        github.com/shadow1ng/fscan/WebScan/lib/eval.go:508 +0x250
github.com/shadow1ng/fscan/WebScan/lib.executePoc.func1({{0xc001957d70, 0x3}, {0xc001957d90, 0xe}, 0x0, {0x0, 0x0}, {0x0, 0x0}, 0x0, ...})
        github.com/shadow1ng/fscan/WebScan/lib/check.go:197 +0x79a
github.com/shadow1ng/fscan/WebScan/lib.executePoc.func2({0xc000c525a0, 0x1, 0xc57145})
        github.com/shadow1ng/fscan/WebScan/lib/check.go:230 +0xb5
github.com/shadow1ng/fscan/WebScan/lib.executePoc(0xc004dd4100, 0xc00243acf0)
        github.com/shadow1ng/fscan/WebScan/lib/check.go:248 +0xbca
github.com/shadow1ng/fscan/WebScan/lib.CheckMultiPoc.func1()
        github.com/shadow1ng/fscan/WebScan/lib/check.go:34 +0x8c
created by github.com/shadow1ng/fscan/WebScan/lib.CheckMultiPoc
        github.com/shadow1ng/fscan/WebScan/lib/check.go:32 +0x5e

goroutine 13 [chan send]:
github.com/shadow1ng/fscan/WebScan/lib.CheckMultiPoc(0xc000c92c00, {0xc000efd000, 0x169, 0xa}, 0x14)
        github.com/shadow1ng/fscan/WebScan/lib/check.go:49 +0x10f
github.com/shadow1ng/fscan/WebScan.Execute({0x14, 0x0, 0x5, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0xc002862d68, ...}, ...})
        github.com/shadow1ng/fscan/WebScan/WebScan.go:48 +0x2d8
github.com/shadow1ng/fscan/WebScan.WebScan(0xc000138d00)
        github.com/shadow1ng/fscan/WebScan/WebScan.go:31 +0x1b8
github.com/shadow1ng/fscan/Plugins.WebTitle(0xc000138d00)
        github.com/shadow1ng/fscan/Plugins/webtitle.go:26 +0x145
reflect.Value.call({0xb44a40, 0xeeaa98, 0x13}, {0xc534cf, 0x4}, {0xc000236018, 0x1, 0x1})
        reflect/value.go:543 +0x814
reflect.Value.Call({0xb44a40, 0xeeaa98, 0xc562dc}, {0xc000236018, 0x1, 0x1})
        reflect/value.go:339 +0xc5
github.com/shadow1ng/fscan/Plugins.ScanFunc(0x199fcb0, {0xc562dc, 0x0}, {0xc000051fc0, 0x1, 0x0})
        github.com/shadow1ng/fscan/Plugins/scanner.go:120 +0x1d4
github.com/shadow1ng/fscan/Plugins.AddScan.func1()
        github.com/shadow1ng/fscan/Plugins/scanner.go:99 +0xf4
created by github.com/shadow1ng/fscan/Plugins.AddScan
        github.com/shadow1ng/fscan/Plugins/scanner.go:95 +0x145

goroutine 43735 [select]:
net/http.(*Transport).getConn(0xc000147a40, 0xc02326cc40, {{}, 0x0, {0xc02a003280, 0x4}, {0xc0161b7650, 0x12}, 0x0})
        net/http/transport.go:1372 +0x5d2
net/http.(*Transport).roundTrip(0xc000147a40, 0xc016528200)
        net/http/transport.go:581 +0x774
net/http.(*Transport).RoundTrip(0xc016528200, 0xfab0c0)
        net/http/roundtrip.go:18 +0x19
net/http.send(0xc016528000, {0xfab0c0, 0xc000147a40}, {0xc2f020, 0x4b5f01, 0x196fae0})
        net/http/client.go:252 +0x5d8
net/http.(*Client).send(0xc0003f4a50, 0xc016528000, {0xc01f6fb930, 0x76, 0x196fae0})
        net/http/client.go:176 +0x9b
net/http.(*Client).do(0xc0003f4a50, 0xc016528000)
        net/http/client.go:725 +0x908
net/http.(*Client).Do(...)
        net/http/client.go:593
github.com/shadow1ng/fscan/WebScan/lib.DoRequest(0xc0172cc4e0, 0x0)
        github.com/shadow1ng/fscan/WebScan/lib/eval.go:508 +0x250
github.com/shadow1ng/fscan/WebScan/lib.executePoc.func1({{0xc002434400, 0x3}, {0xc002102b70, 0x22}, 0x0, {0x0, 0x0}, {0x0, 0x0}, 0x0, ...})
        github.com/shadow1ng/fscan/WebScan/lib/check.go:197 +0x79a
github.com/shadow1ng/fscan/WebScan/lib.executePoc.func2({0xc0026fe900, 0x2, 0xc57145})
        github.com/shadow1ng/fscan/WebScan/lib/check.go:230 +0xb5
github.com/shadow1ng/fscan/WebScan/lib.executePoc(0xc001487d00, 0xc00243a1b0)
        github.com/shadow1ng/fscan/WebScan/lib/check.go:245 +0xb25
github.com/shadow1ng/fscan/WebScan/lib.CheckMultiPoc.func1()
        github.com/shadow1ng/fscan/WebScan/lib/check.go:34 +0x8c
created by github.com/shadow1ng/fscan/WebScan/lib.CheckMultiPoc
        github.com/shadow1ng/fscan/WebScan/lib/check.go:32 +0x5e

goroutine 73799 [select]:
net.(*netFD).connect.func2()
        net/fd_unix.go:119 +0x9e
created by net.(*netFD).connect
        net/fd_unix.go:118 +0x385

```

**Comment by shadow1ng** [comment]
根据报错信息，我在fscan/WebScan/lib/check.go:176加了个锁。师傅下载源码再编译试试？

**Comment by KrystianLi** [comment]
好的，我试试

**Comment by KrystianLi** [comment]
好的，我试试

**Comment by shadow1ng** [comment]
后面发现是map 导致的变量竞争。新分配一个对象地址就行了
![5a9fc3d4a9d3172f75b4a1e425d3a1a](https://user-images.githubusercontent.com/39651966/167989491-573e892f-bc16-423d-9948-e3ef02c46c55.png)
![d96866fa11b4f12d018666bb316adea](https://user-images.githubusercontent.com/39651966/167989494-7bf8c171-6823-45d3-ba9e-8369c6fc07d1.png)
