### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by ymbzd** [shadow1ng/fscan#172]
goroutine 54494 [runnable]:
internal/poll.runtime_pollWait(0x7f8d2c2a35c8, 0x72)
        runtime/netpoll.go:229 +0x89
internal/poll.(*pollDesc).wait(0xc00aeb0d80, 0xc0145b5000, 0x0)
        internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
        internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc00aeb0d80, {0xc0145b5000, 0x1000, 0x1000})
        internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc00aeb0d80, {0xc0145b5000, 0x436067, 0xc001c0ec30})
        net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc01c90ae10, {0xc0145b5000, 0x12, 0xc00001b860})
        net/net.go:183 +0x45
net/http.(*persistConn).Read(0xc00a7f86c0, {0xc0145b5000, 0xc00237d140, 0xc001c0ed30})
        net/http/transport.go:1926 +0x4e
bufio.(*Reader).fill(0xc00efef680)
        bufio/bufio.go:101 +0x103
bufio.(*Reader).Peek(0xc00efef680, 0x1)
        bufio/bufio.go:139 +0x5d
net/http.(*persistConn).readLoop(0xc00a7f86c0)
        net/http/transport.go:2087 +0x1ac
created by net/http.(*Transport).dialConn
        net/http/transport.go:1747 +0x1e05

goroutine 55051 [select]:
golang.org/x/crypto/ssh.(*handshakeTransport).kexLoop(0xc012b3e160)
        golang.org/x/crypto@v0.0.0-20210513164829-c07d793c2f9a/ssh/handshake.go:268 +0x485
created by golang.org/x/crypto/ssh.newClientTransport
        golang.org/x/crypto@v0.0.0-20210513164829-c07d793c2f9a/ssh/handshake.go:135 +0x23d
![image](https://user-images.githubusercontent.com/39881690/168131401-e97d3b81-1120-48e0-8552-e459ed48bd26.png)

**Comment by DatangST** [comment]
一直出现报错

**Comment by shadow1ng** [comment]
有完整报错.txt嘛？ 图片里没看到报错对应的触发点

**Comment by ymbzd** [comment]
一直在报错已经超过cmd的上线而且没法直接输出到txt里   只截取了cmd窗口能放下的
[https://store1.gofile.io/download/ab463d29-3f42-468a-87d0-d21f9960bc1d/5.txt](url)

**Comment by shadow1ng** [comment]
有开头和结尾的报错信息嘛？

**Comment by ymbzd** [comment]
开头

                     fscan version: 1.7.1
fatal error: concurrent map writes
fatal error: concurrent map writes

goroutine 6113 [running]:
runtime.throw({0x161f914, 0xe97c85})
        runtime/panic.go:1198 +0x76 fp=0xc007b6f538 sp=0xc007b6f508 pc=0xde68f6
runtime.mapassign_faststr(0x1527060, 0xc000891890, {0xc000509c70, 0xa})
        runtime/map_faststr.go:294 +0x38b fp=0xc007b6f5a0 sp=0xc007b6f538 pc=0xdc2f2b
github.com/shadow1ng/fscan/WebScan/lib.executePoc.func1({{0xc000509c60, 0x3}, {0xc000ec6840, 0x51}, 0xc000891890, {0x0, 0x0}, {0x0, 0x0}, 0x0, ...})
        github.com/shadow1ng/fscan/WebScan/lib/check.go:176 +0xaef fp=0xc007b6f878 sp=0xc007b6f5a0 pc=0x142f42f
github.com/shadow1ng/fscan/WebScan/lib.executePoc.func2({0xc00121eba0, 0x1, 0x16116e9})
        github.com/shadow1ng/fscan/WebScan/lib/check.go:230 +0xb5 fp=0xc007b6f960 sp=0xc007b6f878 pc=0x142e8d5
github.com/shadow1ng/fscan/WebScan/lib.executePoc(0xc00a01ca00, 0xc001002750)
        github.com/shadow1ng/fscan/WebScan/lib/check.go:245 +0xb25 fp=0xc007b6ff38 sp=0xc007b6f960 pc=0x142db45
github.com/shadow1ng/fscan/WebScan/lib.CheckMultiPoc.func1()
        github.com/shadow1ng/fscan/WebScan/lib/check.go:34 +0x8c fp=0xc007b6ffe0 sp=0xc007b6ff38 pc=0x142cf2c
runtime.goexit()
        runtime/asm_amd64.s:1581 +0x1 fp=0xc007b6ffe8 sp=0xc007b6ffe0 pc=0xe14281
created by github.com/shadow1ng/fscan/WebScan/lib.CheckMultiPoc
        github.com/shadow1ng/fscan/WebScan/lib/check.go:32 +0x5e

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0x1)
        runtime/sema.go:56 +0x25
sync.(*WaitGroup).Wait(0xc00088a7f8)
        sync/waitgroup.go:130 +0x71
github.com/shadow1ng/fscan/Plugins.Scan({{0xc00088a7f8, 0xe}, {0xc00088a807, 0x5}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...})
        github.com/shadow1ng/fscan/Plugins/scanner.go:85 +0x505
main.main()
        github.com/shadow1ng/fscan/main.go:15 +0x98

goroutine 6 [syscall, locked to thread]:
syscall.Syscall6(0x7ffec41c4fd0, 0x5, 0xa34, 0xc001725310, 0x49, 0xc00006dd84, 0x0, 0x0)
        runtime/syscall_windows.go:493 +0xfa
syscall.WriteFile(0xc001dc6780, {0xc001725310, 0x49, 0x80000000000}, 0xc00006dd84, 0x0)
        syscall/zsyscall_windows.go:1166 +0xbe
syscall.Write(0xc001dc6780, {0xc001725310, 0x160dea4, 0x14ff7c0})
        syscall/syscall_windows.go:405 +0x2e
internal/poll.(*FD).Write(0xc001dc6780, {0xc001725310, 0x49, 0x50})
        internal/poll/fd_windows.go:620 +0x25d
os.(*File).write(...)
        os/file_posix.go:49
os.(*File).Write(0xc001d900b0, {0xc001725310, 0x441, 0x18a6630})
        os/file.go:176 +0x65
github.com/shadow1ng/fscan/common.WriteFile({0xc00132c280, 0xc000006018}, {0x161479b, 0xa})
        github.com/shadow1ng/fscan/common/log.go:50 +0x17d
github.com/shadow1ng/fscan/common.SaveLog()
        github.com/shadow1ng/fscan/common/log.go:37 +0x148
created by github.com/shadow1ng/fscan/common.init.0
        github.com/shadow1ng/fscan/common/log.go:22 +0x25

goroutine 4553 [IO wait]:
internal/poll.runtime_pollWait(0x20636bb4bd0, 0x77)
        runtime/netpoll.go:229 +0x89
internal/poll.(*pollDesc).wait(0x28, 0x28, 0x0)
        internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.execIO(0xc0055374e8, 0x18a7630)
        internal/poll/fd_windows.go:175 +0xe5
internal/poll.(*FD).ConnectEx(0xc005537400, {0x196f8e0, 0xc00a0b0be0})
        internal/poll/fd_windows.go:800 +0x57
net.(*netFD).connect(0xc005537400, {0x19809e8, 0xc009bfcd80}, {0x0, 0x0}, {0x196f8e0, 0xc00a0b0be0})
        net/fd_windows.go:106 +0x3cf
net.(*netFD).dial(0xc005537400, {0x19809e8, 0xc009bfcd80}, {0x1986608, 0x0}, {0x1986608, 0xc00a3196e0}, 0xc0063394c8)
        net/sock_posix.go:150 +0x395
net.socket({0x19809e8, 0xc009bfcd80}, {0x160d894, 0x3}, 0x2, 0x1, 0x18a6618, 0xb8, {0x1986608, 0x0}, ...)
        net/sock_posix.go:71 +0x2b4
net.internetSocket({0x19809e8, 0xc009bfcd80}, {0x160d894, 0x3}, {0x1986608, 0x0}, {0x1986608, 0xc00a3196e0}, 0xc00a31b0e0, 0x0, ...)
        net/ipsock_posix.go:142 +0x205
net.(*sysDialer).doDialTCP(0xc00a087b80, {0x19809e8, 0xc009bfcd80}, 0x0, 0x152bd00)
        net/tcpsock_posix.go:66 +0xa5
net.(*sysDialer).dialTCP(0xc009bfcd80, {0x19809e8, 0xc009bfcd80}, 0xc001069c00, 0xc001069880)
        net/tcpsock_posix.go:62 +0x59
net.(*sysDialer).dialSingle(0xc00a087b80, {0x19809e8, 0xc009bfcd80}, {0x1979078, 0xc00a3196e0})
        net/dial.go:583 +0x28b
net.(*sysDialer).dialSerial(0xc00a087b80, {0x19809e8, 0xc009bfcd80}, {0xc00a0fddc0, 0x1, 0x160de40})
        net/dial.go:551 +0x312
net.(*Dialer).DialContext(0xc00006ef00, {0x19809e8, 0xc009bfcd80}, {0x160d894, 0x20638ec8228}, {0xc00a0ef4e8, 0x20})
        net/dial.go:428 +0x736
net/http.(*Transport).dial(0xc009bfcd80, {0x19809e8, 0xc009bfcd80}, {0x160d894, 0xe15b00}, {0xc00a0ef4e8, 0x15cbee0})
        net/http/transport.go:1166 +0xda
net/http.(*Transport).dialConn(0xc000089b80, {0x19809e8, 0xc009bfcd80}, {{}, 0x0, {0xc005755680, 0x5}, {0xc00a0ef4e8, 0x13}, 0x0})
        net/http/transport.go:1604 +0x845
net/http.(*Transport).dialConnFor(0x120c1c6, 0xc004c66fd0)
        net/http/transport.go:1446 +0xb0
created by net/http.(*Transport).queueForDial
        net/http/transport.go:1427 +0x1cf

goroutine 6293 [select]:
net.(*netFD).connect.func2()
        net/fd_windows.go:95 +0x77
created by net.(*netFD).connect
        net/fd_windows.go:94 +0x3b2

goroutine 2190 [select]:
net/http.(*Transport).getConn(0xc000089b80, 0xc001ab0dc0, {{}, 0x0, {0xc000bfe8a0, 0x4}, {0xc000712858, 0x11}, 0x0})
        net/http/transport.go:1372 +0x5d2
net/http.(*Transport).roundTrip(0xc000089b80, 0xc00080ba00)
        net/http/transport.go:581 +0x774
net/http.(*Transport).RoundTrip(0xc00080ba00, 0x196f540)
        net/http/roundtrip.go:18 +0x19
net/http.send(0xc00080b700, {0x196f540, 0xc000089b80}, {0x15e9b00, 0xe74b01, 0x23382c0})
        net/http/client.go:252 +0x5d8
net/http.(*Client).send(0xc00036d3e0, 0xc00080b700, {0x8, 0x0, 0x23382c0})
        net/http/client.go:176 +0x9b
net/http.(*Client).do(0xc00036d3e0, 0xc00080b700)
        net/http/client.go:725 +0x908
net/http.(*Client).Do(...)
        net/http/client.go:593
github.com/shadow1ng/fscan/WebScan/lib.DoRequest(0xc000ea5680, 0x0)
        github.com/shadow1ng/fscan/WebScan/lib/eval.go:508 +0x250
github.com/shadow1ng/fscan/WebScan/lib.executePoc.func1({{0xc000b846d0, 0x3}, {0xc00068cc18, 0x18}, 0x0, {0x0, 0x0}, {0x0, 0x0}, 0x0, ...})
        github.com/shadow1ng/fscan/WebScan/lib/check.go:197 +0x79a
github.com/shadow1ng/fscan/WebScan/lib.executePoc.func2({0xc00121f440, 0x1, 0x16116e9})
        github.com/shadow1ng/fscan/WebScan/lib/check.go:230 +0xb5
github.com/shadow1ng/fscan/WebScan/lib.executePoc(0xc001417400, 0xc001003b90)
        github.com/shadow1ng/fscan/WebScan/lib/check.go:245 +0xb25
github.com/shadow1ng/fscan/WebScan/lib.CheckMultiPoc.func1()
        github.com/shadow1ng/fscan/WebScan/lib/check.go:34 +0x8c
created by github.com/shadow1ng/fscan/WebScan/lib.CheckMultiPoc
        github.com/shadow1ng/fscan/WebScan/lib/check.go:32 +0x5e

goroutine 2188 [select]:
net/http.(*Transport).getConn(0xc000089b80, 0xc006fc9080, {{}, 0x0, {0xc00bebd980, 0x4}, {0xc0084da510, 0x11}, 0x0})
        net/http/transport.go:1372 +0x5d2
net/http.(*Transport).roundTrip(0xc000089b80, 0xc0083fe100)


结尾就是上面txt里的内容

**Comment by DatangST** [comment]
行我在试试



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月17日(星期二) 下午3:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [shadow1ng/fscan] 运行报错 (Issue #172)





 
是poc模块 map竞争的原因。师傅重新更新下代码或exe再试试？

**Comment by DatangST** [comment]
还是不可以，一直运行报错。B段的时候卡卡一顿错误









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shadow1ng/fscan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月17日(星期二) 下午3:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shadow1ng/fscan] 运行报错 (Issue #172)





 
是poc模块 map竞争的原因。师傅重新更新下代码或exe再试试？

**Comment by shadow1ng** [comment]
还是一样的报错？奇怪我这边没复现出来

**Comment by shadow1ng** [comment]
又尝试修了一次
