### ISSUE TITLE
RDP密码爆破模块报错

### ISSUE THREAD

**Issue by Gitqiubai** [shadow1ng/fscan#233]
### 1. 软件版本
```
fscan版本：1.8.1
操作系统：linux
```
### 2. 测试环境
```
windows server 2008 r2
RDP默认3389端口
```
### 3. 报错信息
```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x79d3e9]

goroutine 643 [running]:
github.com/tomatome/grdp/protocol/sec.(*Client).sendClientRandom(0xc0003141e0)
	github.com/tomatome/grdp@v0.0.0-20211231062539-be8adab7eaf3/protocol/sec/sec.go:630 +0x149
github.com/tomatome/grdp/protocol/sec.(*Client).connect(0xc0003141e0, {0xc000336d00, 0x3, 0x4}, {0xc000066440, 0x2, 0x2}, 0x3ea, {0xc00046cde0, 0x2, ...})
	github.com/tomatome/grdp@v0.0.0-20211231062539-be8adab7eaf3/protocol/sec/sec.go:463 +0x308
reflect.Value.call({0xb5f140, 0xc0002f8270, 0x13}, {0xc4db0a, 0x4}, {0xc0004dd920, 0x4, 0x4})
	reflect/value.go:543 +0x814
reflect.Value.Call({0xb5f140, 0xc0002f8270, 0x436096}, {0xc0004dd920, 0x4, 0x4})
	reflect/value.go:339 +0xc5
github.com/tomatome/grdp/emission.(*Emitter).callListeners.func1({0xb5f140, 0xc0002f8270, 0x0})
	github.com/tomatome/grdp@v0.0.0-20211231062539-be8adab7eaf3/emission/emitter.go:226 +0x439
created by github.com/tomatome/grdp/emission.(*Emitter).callListeners
	github.com/tomatome/grdp@v0.0.0-20211231062539-be8adab7eaf3/emission/emitter.go:201 +0x20f
```

  我自己看了一下报错，错误是在grdp依赖库里爆出来的，能力有限具体出错的地方在哪儿debug了半天也没找出来，应该不是主动用panic抛出的异常，看报错应该是那个参数指针空了，这个bug只要一出现整个代码运行就会终止，在扫描大网段的时候造成的损失很严重。

**Comment by evasilence** [comment]
同样遇到这样的问题，大佬有没有相关的解决方案或者思路，跪求

**Comment by shadow1ng** [comment]
可以分批扫描。先扫完其他的，最后再-p 3389，针对3389爆破。  可以直接-hf ipport.txt，直接导入之前的端口扫描记录
