### ISSUE TITLE
扫描的时候报错

### ISSUE THREAD

**Issue by spac3wh1te** [shadow1ng/fscan#248]
```
start vulscan
server=10.1.7.1;user id=sa;password=123456;port=1433;encrypt=disable;timeout=3s
panic: reflect: call of reflect.Value.Type on zero Value

goroutine 52647 [running]:
reflect.Value.typeSlow({0x0, 0x0, 0x0})
  reflect/value.go:2534 +0x13e
reflect.Value.Type(...)
  reflect/value.go:2529
github.com/shadow1ng/fscan/Plugins.ScanFunc(0xa446020, {0xa37239b, 0x4}, {0xa5b3fe4, 0x1, 0x1})
  github.com/shadow1ng/fscan/Plugins/scanner.go:110 +0xe0
github.com/shadow1ng/fscan/Plugins.AddScan.func1()
  github.com/shadow1ng/fscan/Plugins/scanner.go:98 +0xce
created by github.com/shadow1ng/fscan/Plugins.AddScan
  github.com/shadow1ng/fscan/Plugins/scanner.go:94 +0xf7
```

**Comment by shadow1ng** [comment]
运行命令是啥？
