### ISSUE TITLE
师傅，最新版编译失败了。

### ISSUE THREAD

**Issue by ctqch** [shadow1ng/fscan#262]
师傅，RDP爆破失败了。

扫描的RDP服务器不是默认端口，这个我编译的时候已经在config.go里改过了默认端口。

start vulscan
panic: reflect: call of reflect.Value.Call on zero Value

goroutine 1184 [running]:
reflect.flag.mustBe(...)
        reflect/value.go:223
reflect.Value.Call({0x0?, 0x0?, 0xc00054608a?}, {0xc000193f78?, 0x0?, 0xc000193f
01?})
        reflect/value.go:368 +0x118
github.com/shadow1ng/fscan/Plugins.ScanFunc(0x1301385?, 0xc000168140)
        github.com/shadow1ng/fscan/Plugins/scanner.go:121 +0x196
github.com/shadow1ng/fscan/Plugins.AddScan.func1()
        github.com/shadow1ng/fscan/Plugins/scanner.go:109 +0xb7
created by github.com/shadow1ng/fscan/Plugins.AddScan
        github.com/shadow1ng/fscan/Plugins/scanner.go:105 +0x18c
panic: reflect: call of reflect.Value.Call on zero Value

goroutine 1182 [running]:
reflect.flag.mustBe(...)
        reflect/value.go:223
reflect.Value.Call({0x0?, 0x0?, 0xc000546080?}, {0xc000511f78?, 0x0?, 0xc000511f
01?})
        reflect/value.go:368 +0x118
github.com/shadow1ng/fscan/Plugins.ScanFunc(0x1301385?, 0xc0001680a0)
        github.com/shadow1ng/fscan/Plugins/scanner.go:121 +0x196
github.com/shadow1ng/fscan/Plugins.AddScan.func1()
        github.com/shadow1ng/fscan/Plugins/scanner.go:109 +0xb7
created by github.com/shadow1ng/fscan/Plugins.AddScan
        github.com/shadow1ng/fscan/Plugins/scanner.go:105 +0x18c
panic: reflect: call of reflect.Value.Call on zero Value

goroutine 1271 [running]:
reflect.flag.mustBe(...)
        reflect/value.go:223
reflect.Value.Call({0x0?, 0x0?, 0xc0005460b0?}, {0xc00044df78?, 0x13e2fa5?, 0x0?
})
        reflect/value.go:368 +0x118
github.com/shadow1ng/fscan/Plugins.ScanFunc(0x1301385?, 0xc0001685a0)
        github.com/shadow1ng/fscan/Plugins/scanner.go:121 +0x196
github.com/shadow1ng/fscan/Plugins.AddScan.func1()
        github.com/shadow1ng/fscan/Plugins/scanner.go:109 +0xb7
created by github.com/shadow1ng/fscan/Plugins.AddScan
        github.com/shadow1ng/fscan/Plugins/scanner.go:105 +0x18c

C:\Users\admin\admin>

**Comment by ZacharyZcR** [comment]
已经在dev分支中修复这个持续了多年的问题
