### ISSUE TITLE
build mipsel error

### ISSUE THREAD

**Issue by tower111** [shadow1ng/fscan#302]
mips 32位有支持吗，这里构建好了，但是在运行的时候失败了

(base) ➜  fscan git:(main) ✗ GOOS=linux GOARCH=mipsle go build -a -ldflags="-s -w" -trimpath
(base) ➜  fscan git:(main) ✗ qemu-mipsel ./fscan
fatal error: sigaction failed

runtime stack:
runtime.throw({0xb2d07b, 0x10})
	runtime/panic.go:1047 +0x54 fp=0x7ffff3ec sp=0x7ffff3d8 pc=0x56338
runtime.sysSigaction.func1()
	runtime/os_linux.go:555 +0x4c fp=0x7ffff3f8 sp=0x7ffff3ec pc=0x8e8f4
runtime.sysSigaction(0x41, 0x7ffff430, 0x0)
	runtime/os_linux.go:554 +0x7c fp=0x7ffff410 sp=0x7ffff3f8 pc=0x527e8
runtime.sigaction(0x41, 0x7ffff430, 0x0)
	runtime/sigaction.go:15 +0x2c fp=0x7ffff420 sp=0x7ffff410 pc=0x721e8
runtime.setsig(0x41, 0x73cec)
	runtime/os_linux.go:502 +0xb8 fp=0x7ffff44c sp=0x7ffff420 pc=0x526bc
runtime.initsig(0x0)
	runtime/signal_unix.go:148 +0x298 fp=0x7ffff480 sp=0x7ffff44c pc=0x73470
runtime.mstartm0()
	runtime/proc.go:1523 +0x70 fp=0x7ffff488 sp=0x7ffff480 pc=0x5dbe0
runtime.mstart1()
	runtime/proc.go:1495 +0x94 fp=0x7ffff498 sp=0x7ffff488 pc=0x5dad8
runtime.mstart0()
	runtime/proc.go:1456 +0x78 fp=0x7ffff4ac sp=0x7ffff498 pc=0x5da20
runtime.mstart()
	runtime/asm_mipsx.s:89 +0x14 fp=0x7ffff4b0 sp=0x7ffff4ac pc=0x945e4

goroutine 1 [runnable]:
runtime.main()
	runtime/proc.go:145 fp=0x18447ec sp=0x18447ec pc=0x59c84
runtime.goexit()
	runtime/asm_mipsx.s:617 +0x4 fp=0x18447ec sp=0x18447ec pc=0x96a18

**Comment by ZacharyZcR** [comment]
mipsle 已在 goreleaser 构建目标中。QEMU 的 sigaction 报错是模拟器兼容性问题，非 fscan 自身问题。如需 mips64le 支持请另开 issue。
