### ISSUE TITLE
-np存在问题？

### ISSUE THREAD

**Issue by s1g0day** [shadow1ng/fscan#328]
### 测试1：版本1.8.3
问题：我尝试了fscan_arm64、fscan_amd64、fscan.exe,，都是类似的问题，不加np就能正常用，测试调整线程t为10也一样。
问题原因：可能是不支持8位的掩码，修改为10.0.0.1/16、10.0.0.1/24后就能正常使用(其他版本也一样)，具体多少位未测试。
```
fscan_amd64 -h 10.0.0.1/8 -nopoc -o 10.log

   ___                              _    
  / _ \     ___  ___ _ __ __ _  ___| | __ 
 / /_\/____/ __|/ __| '__/ _` |/ __| |/ /
/ /_\\_____\__ \ (__| | | (_| | (__|   <    
\____/     |___/\___|_|  \__,_|\___|_|\_\   
                     fscan version: 1.8.3
start infoscan
(icmp) Target 10.0.1.254      is alive
```

```
fscan_amd64 -h 10.0.0.1/8 -nopoc -np -o 10.log

   ___                              _    
  / _ \     ___  ___ _ __ __ _  ___| | __ 
 / /_\/____/ __|/ __| '__/ _` |/ __| |/ /
/ /_\\_____\__ \ (__| | | (_| | (__|   <    
\____/     |___/\___|_|  \__,_|\___|_|\_\   
                     fscan version: 1.8.3
start infoscan
fatal error: runtime: out of memory

runtime stack:
runtime.throw({0xd6970a?, 0x2030?})
        runtime/panic.go:1077 +0x5c fp=0xc00010bdf8 sp=0xc00010bdc8 pc=0x438edc
runtime.sysMapOS(0xc006c00000, 0xcc800000?)
        runtime/mem_linux.go:167 +0x116 fp=0xc00010be40 sp=0xc00010bdf8 pc=0x41a356
runtime.sysMap(0x1b44c20?, 0x42ef60?, 0x1b54de8?)
        runtime/mem.go:155 +0x34 fp=0xc00010be70 sp=0xc00010be40 pc=0x419d34
runtime.(*mheap).grow(0x1b44c20, 0x66300?)
        runtime/mheap.go:1533 +0x236 fp=0xc00010bee0 sp=0xc00010be70 pc=0x42be16
runtime.(*mheap).allocSpan(0x1b44c20, 0x66300, 0x0, 0x9?)
        runtime/mheap.go:1250 +0x1b0 fp=0xc00010bf80 sp=0xc00010bee0 pc=0x42b530
runtime.(*mheap).alloc.func1()
        runtime/mheap.go:968 +0x5c fp=0xc00010bfc8 sp=0xc00010bf80 pc=0x42afbc
traceback: unexpected SPWRITE function runtime.systemstack
runtime.systemstack()
        runtime/asm_amd64.s:509 +0x4a fp=0xc00010bfd8 sp=0xc00010bfc8 pc=0x468d2a

goroutine 1 [running]:
runtime.systemstack_switch()
        runtime/asm_amd64.s:474 +0x8 fp=0xc000585830 sp=0xc000585820 pc=0x468cc8
runtime.(*mheap).alloc(0xcc600000?, 0x66300?, 0xb0?)
        runtime/mheap.go:962 +0x5b fp=0xc000585878 sp=0xc000585830 pc=0x42af1b
runtime.(*mcache).allocLarge(0x7f238c24e600?, 0xcc600000, 0x60?)
        runtime/mcache.go:234 +0x85 fp=0xc0005858c0 sp=0xc000585878 pc=0x418f05
runtime.mallocgc(0xcc600000, 0xc93640, 0x1)
        runtime/malloc.go:1123 +0x4f6 fp=0xc000585928 sp=0xc0005858c0 pc=0x410116
runtime.makechan(0x0?, 0x8840000)
        runtime/chan.go:107 +0xe5 fp=0xc000585968 sp=0xc000585928 pc=0x408785
github.com/shadow1ng/fscan/Plugins.PortScan({0xc005970000, 0xa0000, 0xd5b444?}, {0xc00016e480, 0x45c}, 0x3)
        github.com/shadow1ng/fscan/Plugins/portscan.go:43 +0x371 fp=0xc000585b68 sp=0xc000585968 pc=0xbaa451
github.com/shadow1ng/fscan/Plugins.Scan({{0x7fff07b29550, 0xa}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0, 0x0}})
        github.com/shadow1ng/fscan/Plugins/scanner.go:41 +0x4ab fp=0xc000585eb8 sp=0xc000585b68 pc=0xbb03ab
main.main()
        github.com/shadow1ng/fscan/main.go:15 +0x79 fp=0xc000585f40 sp=0xc000585eb8 pc=0xbb8bd9
runtime.main()
        runtime/proc.go:267 +0x2bb fp=0xc000585fe0 sp=0xc000585f40 pc=0x43b8bb
runtime.goexit()
        runtime/asm_amd64.s:1650 +0x1 fp=0xc000585fe8 sp=0xc000585fe0 pc=0x46ab21

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:398 +0xce fp=0xc00005cfa8 sp=0xc00005cf88 pc=0x43bd0e
runtime.goparkunlock(...)
        runtime/proc.go:404
runtime.forcegchelper()
        runtime/proc.go:322 +0xb3 fp=0xc00005cfe0 sp=0xc00005cfa8 pc=0x43bb93
runtime.goexit()
        runtime/asm_amd64.s:1650 +0x1 fp=0xc00005cfe8 sp=0xc00005cfe0 pc=0x46ab21
created by runtime.init.6 in goroutine 1
        runtime/proc.go:310 +0x1a

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:398 +0xce fp=0xc00005d778 sp=0xc00005d758 pc=0x43bd0e
runtime.goparkunlock(...)
        runtime/proc.go:404
runtime.bgsweep(0x0?)
        runtime/mgcsweep.go:321 +0xdf fp=0xc00005d7c8 sp=0xc00005d778 pc=0x427d7f
runtime.gcenable.func1()
        runtime/mgc.go:200 +0x25 fp=0xc00005d7e0 sp=0xc00005d7c8 pc=0x41cea5
runtime.goexit()
        runtime/asm_amd64.s:1650 +0x1 fp=0xc00005d7e8 sp=0xc00005d7e0 pc=0x46ab21
created by runtime.gcenable in goroutine 1
        runtime/mgc.go:200 +0x66

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc00007c000?, 0x11035a8?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:398 +0xce fp=0xc00005df70 sp=0xc00005df50 pc=0x43bd0e
runtime.goparkunlock(...)
        runtime/proc.go:404
runtime.(*scavengerState).park(0x1b2c600)
        runtime/mgcscavenge.go:425 +0x49 fp=0xc00005dfa0 sp=0xc00005df70 pc=0x4255a9
runtime.bgscavenge(0x0?)
        runtime/mgcscavenge.go:658 +0x59 fp=0xc00005dfc8 sp=0xc00005dfa0 pc=0x425b59
runtime.gcenable.func2()
        runtime/mgc.go:201 +0x25 fp=0xc00005dfe0 sp=0xc00005dfc8 pc=0x41ce45
runtime.goexit()
        runtime/asm_amd64.s:1650 +0x1 fp=0xc00005dfe8 sp=0xc00005dfe0 pc=0x46ab21
created by runtime.gcenable in goroutine 1
        runtime/mgc.go:201 +0xa5

goroutine 5 [finalizer wait]:
runtime.gopark(0x400000?, 0x10005c670?, 0x0?, 0x0?, 0x1b5d300?)
        runtime/proc.go:398 +0xce fp=0xc00005c628 sp=0xc00005c608 pc=0x43bd0e
runtime.runfinq()
        runtime/mfinal.go:193 +0x107 fp=0xc00005c7e0 sp=0xc00005c628 pc=0x41bf27
runtime.goexit()
        runtime/asm_amd64.s:1650 +0x1 fp=0xc00005c7e8 sp=0xc00005c7e0 pc=0x46ab21
created by runtime.createfing in goroutine 1
        runtime/mfinal.go:163 +0x3d

goroutine 6 [chan receive]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:398 +0xce fp=0xc00005e6c8 sp=0xc00005e6a8 pc=0x43bd0e
runtime.chanrecv(0xc000112540, 0xc00005e7a8, 0x1)
        runtime/chan.go:583 +0x3cd fp=0xc00005e740 sp=0xc00005e6c8 pc=0x4099ad
runtime.chanrecv2(0x0?, 0x0?)
        runtime/chan.go:447 +0x12 fp=0xc00005e768 sp=0xc00005e740 pc=0x4095d2
github.com/shadow1ng/fscan/common.SaveLog()
        github.com/shadow1ng/fscan/common/log.go:42 +0x4c fp=0xc00005e7e0 sp=0xc00005e768 pc=0x5a3dcc
runtime.goexit()
        runtime/asm_amd64.s:1650 +0x1 fp=0xc00005e7e8 sp=0xc00005e7e0 pc=0x46ab21
created by github.com/shadow1ng/fscan/common.init.0 in goroutine 1
        github.com/shadow1ng/fscan/common/log.go:32 +0x65

goroutine 7 [GC worker (idle)]:
runtime.gopark(0x1274e69714096f?, 0x1?, 0x49?, 0x4f?, 0x0?)
        runtime/proc.go:398 +0xce fp=0xc00005ef50 sp=0xc00005ef30 pc=0x43bd0e
runtime.gcBgMarkWorker()
        runtime/mgc.go:1293 +0xe5 fp=0xc00005efe0 sp=0xc00005ef50 pc=0x41ea25
runtime.goexit()
        runtime/asm_amd64.s:1650 +0x1 fp=0xc00005efe8 sp=0xc00005efe0 pc=0x46ab21
created by runtime.gcBgMarkStartWorkers in goroutine 1
        runtime/mgc.go:1217 +0x1c

goroutine 8 [GC worker (idle)]:
runtime.gopark(0x1274e697e3d9a5?, 0x3?, 0xf9?, 0x73?, 0x0?)
        runtime/proc.go:398 +0xce fp=0xc00005f750 sp=0xc00005f730 pc=0x43bd0e
runtime.gcBgMarkWorker()
        runtime/mgc.go:1293 +0xe5 fp=0xc00005f7e0 sp=0xc00005f750 pc=0x41ea25
runtime.goexit()
        runtime/asm_amd64.s:1650 +0x1 fp=0xc00005f7e8 sp=0xc00005f7e0 pc=0x46ab21
created by runtime.gcBgMarkStartWorkers in goroutine 1
        runtime/mgc.go:1217 +0x1c

goroutine 9 [GC worker (idle)]:
runtime.gopark(0x1274e6998ba1c1?, 0x1?, 0xb3?, 0xc7?, 0x0?)
        runtime/proc.go:398 +0xce fp=0xc00005ff50 sp=0xc00005ff30 pc=0x43bd0e
runtime.gcBgMarkWorker()
        runtime/mgc.go:1293 +0xe5 fp=0xc00005ffe0 sp=0xc00005ff50 pc=0x41ea25
runtime.goexit()
        runtime/asm_amd64.s:1650 +0x1 fp=0xc00005ffe8 sp=0xc00005ffe0 pc=0x46ab21
created by runtime.gcBgMarkStartWorkers in goroutine 1
        runtime/mgc.go:1217 +0x1c

goroutine 17 [GC worker (idle)]:
runtime.gopark(0x1274e689a9c673?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:398 +0xce fp=0xc000058750 sp=0xc000058730 pc=0x43bd0e
runtime.gcBgMarkWorker()
```
### 测试2：版本1.8.2
测试程序: fscan_amd64
结果：添加-np后直接退出程序了
```
./test1 -h 10.0.0.1/8 -nopoc -np -o 10.log

   ___                              _    
  / _ \     ___  ___ _ __ __ _  ___| | __ 
 / /_\/____/ __|/ __| '__/ _` |/ __| |/ /
/ /_\\_____\__ \ (__| | | (_| | (__|   <    
\____/     |___/\___|_|  \__,_|\___|_|\_\   
                     fscan version: 1.8.2
start infoscan
```
### 测试3：版本1.8.1、版本1.8.0、版本1.7.1
测试程序: fscan_amd64
结果：添加-np后还是报内存异常
```
./test2 -h 10.0.0.1/8 -np -nopoc -o 10.log

   ___                              _    
  / _ \     ___  ___ _ __ __ _  ___| | __ 
 / /_\/____/ __|/ __| '__/ _` |/ __| |/ /
/ /_\\_____\__ \ (__| | | (_| | (__|   <    
\____/     |___/\___|_|  \__,_|\___|_|\_\   
                     fscan version: 1.8.1
start infoscan
fatal error: runtime: out of memory

runtime stack:
runtime.throw({0xc602a5, 0xcc800000})
        runtime/panic.go:1198 +0x71
runtime.sysMap(0xc006c00000, 0x4296e0, 0xc000069e90)
        runtime/mem_linux.go:169 +0x96
runtime.(*mheap).grow(0x19895c0, 0x66300)
        runtime/mheap.go:1393 +0x225
runtime.(*mheap).allocSpan(0x19895c0, 0x66300, 0x0, 0x0)
        runtime/mheap.go:1179 +0x165
runtime.(*mheap).alloc.func1()
        runtime/mheap.go:913 +0x69
runtime.systemstack()
        runtime/asm_amd64.s:383 +0x49

goroutine 1 [running]:
runtime.systemstack_switch()
        runtime/asm_amd64.s:350 fp=0xc0001ad968 sp=0xc0001ad960 pc=0x460d00
runtime.(*mheap).alloc(0xcc600000, 0x66300, 0x0, 0x1)
        runtime/mheap.go:907 +0x73 fp=0xc0001ad9b8 sp=0xc0001ad968 pc=0x425933
runtime.(*mcache).allocLarge(0x7fb1594ddaa8, 0xcc600000, 0x60, 0x0)
        runtime/mcache.go:227 +0x89 fp=0xc0001ada18 sp=0xc0001ad9b8 pc=0x4165a9
runtime.mallocgc(0xcc600000, 0xb9e860, 0x1)
        runtime/malloc.go:1082 +0x5c5 fp=0xc0001ada98 sp=0xc0001ada18 pc=0x40cb25
runtime.makechan(0x0, 0x8840000)
        runtime/chan.go:106 +0xe5 fp=0xc0001adad8 sp=0xc0001ada98 pc=0x405005
github.com/shadow1ng/fscan/Plugins.PortScan({0xc0022b6000, 0xa0000, 0x0}, {0xc0000e4480, 0x45c}, 0x3)
        github.com/shadow1ng/fscan/Plugins/portscan.go:39 +0x2f4 fp=0xc0001adcc8 sp=0xc0001adad8 pc=0xac6db4
github.com/shadow1ng/fscan/Plugins.Scan({{0x7fff84811562, 0xa}, {0xc0000e4480, 0x45c}, {0x0, 0x0}, {0x0, 0x0, 0x0}})
        github.com/shadow1ng/fscan/Plugins/scanner.go:37 +0x310 fp=0xc0001adef8 sp=0xc0001adcc8 pc=0xacd010
main.main()
        github.com/shadow1ng/fscan/main.go:14 +0x85 fp=0xc0001adf80 sp=0xc0001adef8 pc=0xad3545
runtime.main()
        runtime/proc.go:255 +0x227 fp=0xc0001adfe0 sp=0xc0001adf80 pc=0x435cc7
runtime.goexit()
        runtime/asm_amd64.s:1581 +0x1 fp=0xc0001adfe8 sp=0xc0001adfe0 pc=0x462de1

goroutine 6 [sleep]:
time.Sleep(0x2540be400)
        runtime/time.go:193 +0x12e
github.com/shadow1ng/fscan/common.init.0.func1()
        github.com/shadow1ng/fscan/common/flag.go:15 +0x2e
created by github.com/shadow1ng/fscan/common.init.0
        github.com/shadow1ng/fscan/common/flag.go:11 +0x25

goroutine 7 [chan receive]:
github.com/shadow1ng/fscan/common.SaveLog()
        github.com/shadow1ng/fscan/common/log.go:32 +0x54
created by github.com/shadow1ng/fscan/common.init.1
        github.com/shadow1ng/fscan/common/log.go:22 +0x25
```

**Comment by XiaoliChan** [comment]
这个是`-np` 导致会让fscan一次性生成 `10.0.0.0-10.255.255.255`个目标，大量目标会导致fscan OOM，解决办法就是修改源码，在`-np` 情况下也扫描少量目标

**Comment by shadow1ng** [comment]
我明天检查一下哈


------------------ 原始邮件 ------------------
发件人: XiaoliChan ***@***.***&gt;
发送时间: 2024年1月13日 19:25
收件人: shadow1ng/fscan ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [shadow1ng/fscan] -np存在问题？ (Issue #328)





 
这个是-np 导致会让fscan一次性生成 10.0.0.0-10.255.255.255个目标，大量目标会导致fscan OOM，解决办法就是修改源码，在-np 情况下也扫描少量目标

**Comment by shadow1ng** [comment]
fscan目前比较推荐扫/16为主。 
-h 10.0.0.1/8 。扫描/8时,只扫网关和随机IP,避免扫描过多IP。-h 10.0.0.0-10.255.255.255才会硬扫A段。
优化大量IP，一般是用chanel队列比较合适，但扫描流程可能需要改动。所以一直没动

**Comment by XiaoliChan** [comment]
其实有个建议，在遇到8位子网掩码的时候，随机IP替换成常见的网关: ".1 .2 .100 .254 .255"，只扫描网关
![image](https://github.com/shadow1ng/fscan/assets/30458572/b35b3833-ddc8-4b74-b7e8-a1c458267642)

**Comment by s1g0day** [comment]
感谢作者大大回复及维护，由于对代码不熟，所以无法提供修改建议，只能给出一些使用反馈。

我后来又测试了下，发现16段使用-np的时候也会存在这个问题
```
fscan -h 10.1.0.0/16 -np -nopoc -p 1-65535 -o 10.1.log   # 异常
fscan -h 10.1.0.0/16 -np -nopoc  -o 10.1.log  # 正常
```

目前我的解决方法是改变测试思路，先用masscan扫描8段存活，然后再用fscan针对24段进行-np测试
