### ISSUE TITLE
一个较为严重的问题

### ISSUE THREAD

**Issue by hackboy2002** [shadow1ng/fscan#331]
1.8.3版本
![反馈](https://github.com/shadow1ng/fscan/assets/67528417/ca84b8de-3aad-43d2-8fb8-ff1bad5a1f55)
做多端口，带入ip文件加账号密码喷洒时报错
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0xd9278d]

goroutine 6186 [running]:
github.com/tomatome/grdp/protocol/sec.(*Client).sendClientRandom(0xc000d76cd0)
        github.com/tomatome/grdp@v0.0.0-20211231062539-be8adab7eaf3/protocol/sec/sec.go:630 +0x12d
github.com/tomatome/grdp/protocol/sec.(*Client).connect(0xc000d76cd0, {0xc002364980, 0x3, 0x4}, {0xc00033a340, 0x2, 0x2}, 0x3ea, {0xc0024b1cb0, 0x2, ...})
        github.com/tomatome/grdp@v0.0.0-20211231062539-be8adab7eaf3/protocol/sec/sec.go:463 +0x3d4
reflect.Value.call({0x11bf7e0?, 0xc0010506b0?, 0x12c3e20?}, {0x12c4b98, 0x4}, {0xc002320240, 0x4, 0x30?})
        reflect/value.go:596 +0xce7
reflect.Value.Call({0x11bf7e0?, 0xc0010506b0?, 0x960b85?}, {0xc002320240?, 0x12c3e20?, 0x1679ca0?})
        reflect/value.go:380 +0xb9
github.com/tomatome/grdp/emission.(*Emitter).callListeners.func1({0x11bf7e0?, 0xc0010506b0?, 0xc00223473a?})
        github.com/tomatome/grdp@v0.0.0-20211231062539-be8adab7eaf3/emission/emitter.go:226 +0x405
created by github.com/tomatome/grdp/emission.(*Emitter).callListeners in goroutine 6185
        github.com/tomatome/grdp@v0.0.0-20211231062539-be8adab7eaf3/emission/emitter.go:201 +0x7f

**Comment by shadow1ng** [comment]
是扫了多少个IP、端口？ 4G内存？

**Comment by hackboy2002** [comment]
Ip大概6个C段，端口应该是445或者3389出问题了，本地扫的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月4日(周日) 上午9:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [shadow1ng/fscan] 一个较为严重的问题 (Issue #331)




 
是扫了多少个IP、端口？ 4G内存？

**Comment by shadow1ng** [comment]
哦。grpc库有点点问题，报错了

**Comment by shannaburns** [comment]
> 哦。grpc库有点点问题，报错了

现在1.8.4还是有这个问题，也不知道啥原因触发的

**Comment by Labster22** [comment]
同
