### ISSUE TITLE
eorr plz

### ISSUE THREAD

**Issue by soominoh** [shadow1ng/fscan#332]
scanning smb2 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x17cddcb]

goroutine 11 [running]:
github.com/shadow1ng/fscan/Plugins.PortConnect({{0xc00015be27?, 0x0?}, 0x0?}, 0xc000092180, 0x3, 0xc00000b450)
        github.com/shadow1ng/fscan/Plugins/portscan.go:77 +0x12b
github.com/shadow1ng/fscan/Plugins.PortScan.func2()
        github.com/shadow1ng/fscan/Plugins/portscan.go:55 +0x79
created by github.com/shadow1ng/fscan/Plugins.PortScan in goroutine 1
        github.com/shadow1ng/fscan/Plugins/portscan.go:53 +0x3a5
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x17cddcb]

goroutine 82 [running]:
github.com/shadow1ng/fscan/Plugins.PortConnect({{0xc00000b230?, 0x0?}, 0x0?}, 0xc000092180, 0x3, 0xc00000b450)
        github.com/shadow1ng/fscan/Plugins/portscan.go:77 +0x12b
github.com/shadow1ng/fscan/Plugins.PortScan.func2()
        github.com/shadow1ng/fscan/Plugins/portscan.go:55 +0x79
created by github.com/shadow1ng/fscan/Plugins.PortScan in goroutine 1
        github.com/shadow1ng/fscan/Plugins/portscan.go:53 +0x3a5
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x17cddcb]

goroutine 79 [running]:
github.com/shadow1ng/fscan/Plugins.PortConnect({{0xc00049c060?, 0x0?}, 0x0?}, 0xc000092180, 0x3, 0xc00000b450)
        github.com/shadow1ng/fscan/Plugins/portscan.go:77 +0x12b
github.com/shadow1ng/fscan/Plugins.PortScan.func2()
        github.com/shadow1ng/fscan/Plugins/portscan.go:55 +0x79
created by github.com/shadow1ng/fscan/Plugins.PortScan in goroutine 1
        github.com/shadow1ng/fscan/Plugins/portscan.go:53 +0x3a5
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x17cddcb]

goroutine 58 [running]:
github.com/shadow1ng/fscan/Plugins.PortConnect({{0xc00015bf10?, 0x0?}, 0x0?}, 0xc000092180, 0x3, 0xc00000b450)
        github.com/shadow1ng/fscan/Plugins/portscan.go:77 +0x12b
github.com/shadow1ng/fscan/Plugins.PortScan.func2()
        github.com/shadow1ng/fscan/Plugins/portscan.go:55 +0x79
created by github.com/shadow1ng/fscan/Plugins.PortScan in goroutine 1
        github.com/shadow1ng/fscan/Plugins/portscan.go:53 +0x3a5
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x17cddcb]

goroutine 59 [running]:
github.com/shadow1ng/fscan/Plugins.PortConnect({{0xc00015bf20?, 0x0?}, 0x0?}, 0xc000092180, 0x3, 0xc00000b450)
        github.com/shadow1ng/fscan/Plugins/portscan.go:77 +0x12b
github.com/shadow1ng/fscan/Plugins.PortScan.func2()
        github.com/shadow1ng/fscan/Plugins/portscan.go:55 +0x79
created by github.com/shadow1ng/fscan/Plugins.PortScan in goroutine 1
        github.com/shadow1ng/fscan/Plugins/portscan.go:53 +0x3a5
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x17cddcb]

goroutine 12 [running]:
github.com/shadow1ng/fscan/Plugins.PortConnect({{0xc00015be40?, 0x0?}, 0x0?}, 0xc000092180, 0x3, 0xc00000b450)
        github.com/shadow1ng/fscan/Plugins/portscan.go:77 +0x12b
github.com/shadow1ng/fscan/Plugins.PortScan.func2()
        github.com/shadow1ng/fscan/Plugins/portscan.go:55 +0x79
created by github.com/shadow1ng/fscan/Plugins.PortScan in goroutine 1
        github.com/shadow1ng/fscan/Plugins/portscan.go:53 +0x3a5
PS C:\Users\cmc\Desktop\fscan-main\fscan-1.8.3\fscan-1.8.3> .\main.exe -h x.x.x.x/24 -m smb2

**Comment by shadow1ng** [comment]
用新的代码或release也会这样嘛

**Comment by N0rther** [comment]
是的

**Comment by ZacharyZcR** [comment]
Please provide more information.
