### ISSUE TITLE
RDP error scan\brute.

### ISSUE THREAD

**Issue by TheWay-hue** [shadow1ng/fscan#347]
![image](https://github.com/shadow1ng/fscan/assets/64380347/165f72ea-6ca7-420c-b17d-6f67254362db)

**Error**: 

```panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x8d0b6d]

goroutine 137832 [running]:
github.com/tomatome/grdp/protocol/sec.(*Client).sendClientRandom(0xc001078050)
        github.com/tomatome/grdp@v0.0.0-20211231062539-be8adab7eaf3/protocol/sec/sec.go:630 +0x12d
github.com/tomatome/grdp/protocol/sec.(*Client).connect(0xc001078050, {0xc000b7e4c0, 0x3, 0x4}, {0xc00085ea00, 0x2, 0x2}, 0x3ec, {0xc000f81380, 0x2, ...})
        github.com/tomatome/grdp@v0.0.0-20211231062539-be8adab7eaf3/protocol/sec/sec.go:463 +0x3d4
reflect.Value.call({0xd07980?, 0xc0010492e0?, 0xe1bca0?}, {0xe1d58c, 0x4}, {0xc0014939e0, 0x4, 0x30?})
        reflect/value.go:596 +0xce7
reflect.Value.Call({0xd07980?, 0xc0010492e0?, 0x4107c5?}, {0xc0014939e0?, 0xe1bca0?, 0x11ec8e0?})
        reflect/value.go:380 +0xb9
github.com/tomatome/grdp/emission.(*Emitter).callListeners.func1({0xd07980?, 0xc0010492e0?, 0xc0003e23e2?})
        github.com/tomatome/grdp@v0.0.0-20211231062539-be8adab7eaf3/emission/emitter.go:226 +0x405
created by github.com/tomatome/grdp/emission.(*Emitter).callListeners in goroutine 137831
        github.com/tomatome/grdp@v0.0.0-20211231062539-be8adab7eaf3/emission/emitter.go:201 +0x7f```

**Comment by ZacharyZcR** [comment]
已经在dev分支中修复这个持续了多年的问题
