### ISSUE TITLE
Linux 开发的rdp 连接报错

### ISSUE THREAD

**Issue by FynnFbc** [shadow1ng/fscan#383]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x14880ed]

goroutine 169752 [running]:
github.com/tomatome/grdp/protocol/sec.(*Client).sendClientRandom(0xc00277e050)
?github.com/tomatome/grdp@v0.0.0-20211231062539-be8adab7eaf3/protocol/sec/sec.go:630 +0x12d
github.com/tomatome/grdp/protocol/sec.(*Client).connect(0xc00277e050, {0xc0010492c0, 0x3, 0x4}, {0xc00287fc00, 0x2, 0x2}, 0x3ec, {0xc00129eed0, 0x2, ...})
?github.com/tomatome/grdp@v0.0.0-20211231062539-be8adab7eaf3/protocol/sec/sec.go:463 +0x3d4
reflect.Value.call({0x18c0460?, 0xc0024d5020?, 0x19d69c0?}, {0x19d836f, 0x4}, {0xc000ec2f60, 0x4, 0x30?})
?reflect/value.go:596 +0xce7
reflect.Value.Call({0x18c0460?, 0xc0024d5020?, 0xfb0dc5?}, {0xc000ec2f60?, 0x19d69c0?, 0x1dac660?})
?reflect/value.go:380 +0xb9
github.com/tomatome/grdp/emission.(*Emitter).callListeners.func1({0x18c0460?, 0xc0024d5020?, 0xc002dac94a?})
?github.com/tomatome/grdp@v0.0.0-20211231062539-be8adab7eaf3/emission/emitter.go:226 +0x405
created by github.com/tomatome/grdp/emission.(*Emitter).callListeners in goroutine 169751
?github.com/tomatome/grdp@v0.0.0-20211231062539-be8adab7eaf3/emission/emitter.go:201 +0x7f

**Comment by shadow1ng** [comment]
github.com/tomatome/grdp 库没更新，这个rdp协议我也不太会修

**Comment by ZacharyZcR** [comment]
已经在dev分支中修复这个持续了多年的问题
