### ISSUE TITLE
爆破RDP3389端口报错

### ISSUE THREAD

**Issue by Zxc123456zxc** [shadow1ng/fscan#385]
命令  fscan.exe -h 0.0.0.0/24 -nopoc -p 3389 -t 100 -o 1.txt

![image](https://github.com/user-attachments/assets/f440963d-1488-4d8b-8a8a-47fbd83cf2d4)

fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire, 12 minutes]:
sync.runtime_Semacquire(0x1?)
        runtime/sema.go:62 +0x25
sync.(*WaitGroup).Wait(0xc00088a2a0?)
        sync/waitgroup.go:116 +0x48
github.com/shadow1ng/fscan/Plugins.Scan({{0xc00088a2a0, 0xd}, {0xc00088a2ae, 0x4}, {0x0, 0x0}, {0x0, 0x0, 0x0}})
        github.com/shadow1ng/fscan/Plugins/scanner.go:90 +0x7f6
main.main()
        github.com/shadow1ng/fscan/main.go:15 +0x79

goroutine 6 [chan receive, 9 minutes]:
github.com/shadow1ng/fscan/common.SaveLog()
        github.com/shadow1ng/fscan/common/log.go:44 +0x4c
created by github.com/shadow1ng/fscan/common.init.0 in goroutine 1
        github.com/shadow1ng/fscan/common/log.go:34 +0x6a

goroutine 265 [chan send, 9 minutes]:
github.com/shadow1ng/fscan/Plugins.RdpScan(0xc000790af0)
        github.com/shadow1ng/fscan/Plugins/rdp.go:50 +0x3fb
reflect.Value.call({0x159ca00?, 0x1a69fb8?, 0xd5ff0e?}, {0x16d22c4, 0x4}, {0xc0003d1f60, 0x1, 0x1?})
        reflect/value.go:596 +0xca6
reflect.Value.Call({0x159ca00?, 0x1a69fb8?, 0xc000902235?}, {0xc0003d1f60?, 0x12?, 0x158cf00?})
        reflect/value.go:380 +0xb9
github.com/shadow1ng/fscan/Plugins.ScanFunc(0xc000092a80?, 0xc000790af0)
        github.com/shadow1ng/fscan/Plugins/scanner.go:122 +0x159
github.com/shadow1ng/fscan/Plugins.AddScan.func1()
        github.com/shadow1ng/fscan/Plugins/scanner.go:105 +0xab
created by github.com/shadow1ng/fscan/Plugins.AddScan in goroutine 1
        github.com/shadow1ng/fscan/Plugins/scanner.go:101 +0x185

goroutine 245 [chan send, 9 minutes]:
github.com/shadow1ng/fscan/Plugins.RdpScan(0xc0007904b0)
        github.com/shadow1ng/fscan/Plugins/rdp.go:50 +0x3fb
reflect.Value.call({0x159ca00?, 0x1a69fb8?, 0x1b5ccc0?}, {0x16d22c4, 0x4}, {0xc0003f9f60, 0x1, 0x1?})
        reflect/value.go:596 +0xca6
reflect.Value.Call({0x159ca00?, 0x1a69fb8?, 0xc0005a015d?}, {0xc0003f9f60?, 0x2654ec0?, 0xc0003f9f48?})
        reflect/value.go:380 +0xb9
github.com/shadow1ng/fscan/Plugins.ScanFunc(0xc000706310?, 0xc0007904b0)
        github.com/shadow1ng/fscan/Plugins/scanner.go:122 +0x159
github.com/shadow1ng/fscan/Plugins.AddScan.func1()
        github.com/shadow1ng/fscan/Plugins/scanner.go:105 +0xab
created by github.com/shadow1ng/fscan/Plugins.AddScan in goroutine 1
        github.com/shadow1ng/fscan/Plugins/scanner.go:101 +0x185

**Comment by shadow1ng** [comment]
github.com/tomatome/grdp 库没更新，这个rdp协议我也不太会修

**Comment by Zxc123456zxc** [comment]
> github.com/tomatome/grdp 库没更新，这个rdp协议我也不太会修
好的，感谢大哥

**Comment by ZacharyZcR** [comment]
已经在dev分支中修复这个持续了多年的问题
