### ISSUE TITLE
linux 低权限报错

### ISSUE THREAD

**Issue by TryA9ain** [shadow1ng/fscan#77]
`cat /proc/version`
`whoami`
![image](https://user-images.githubusercontent.com/51145610/125598364-9ae4a1d6-8c2e-4f4b-8530-e05fb5706638.png)
```
alive ports len is: 222
start vulscan
panic: setting PGSERVICEFILE not supported

goroutine 14396 [running]:
github.com/lib/pq.parseEnviron.func2(...)
        github.com/lib/pq@v1.10.1/conn.go:1962
github.com/lib/pq.parseEnviron(0xc0003c0a00, 0x49, 0x49, 0xc0001727b0)
        github.com/lib/pq@v1.10.1/conn.go:1985 +0x1245
github.com/lib/pq.NewConnector(0xc00034a050, 0x44, 0xc000bde6a8, 0xc00069efc0, 0xc00069efc0)
        github.com/lib/pq@v1.10.1/connector.go:56 +0x145
github.com/lib/pq.DialOpen(0xd5e2d0, 0xc00069efc0, 0xc00034a050, 0x44, 0x7f9362f1f800, 0x20300000000000, 0x7f9363094fff, 0x7f933bfea4b0)
        github.com/lib/pq@v1.10.1/conn.go:286 +0x39
github.com/lib/pq.Open(...)
        github.com/lib/pq@v1.10.1/conn.go:281
github.com/lib/pq.Driver.Open(0xc00034a050, 0x44, 0x100000012, 0x1364dc8, 0x7f933c4aa7f0, 0x8)
        github.com/lib/pq@v1.10.1/conn.go:54 +0x9f
database/sql.dsnConnector.Connect(...)
        database/sql/sql.go:707
database/sql.(*DB).conn(0xc00040c1a0, 0xd64b90, 0xc0000380b0, 0xc00114e001, 0x0, 0xc000bde900, 0x4ebe0b)
        database/sql/sql.go:1300 +0x184
database/sql.(*DB).PingContext(0xc00040c1a0, 0xd64b90, 0xc0000380b0, 0x44, 0xc00040c1a0)
        database/sql/sql.go:799 +0x90
database/sql.(*DB).Ping(...)
        database/sql/sql.go:816
github.com/shadow1ng/fscan/Plugins.PostgresConn(0xc0000108c0, 0xc5bdce, 0x8, 0xc587a6, 0x6, 0x0, 0x0, 0x0)
        github.com/shadow1ng/fscan@v0.0.0-20210529121601-162d1dd3a3d1/Plugins/postgres.go:44 +0x2e7
github.com/shadow1ng/fscan/Plugins.PostgresScan(0xc0000108c0, 0x0, 0x0)
        github.com/shadow1ng/fscan@v0.0.0-20210529121601-162d1dd3a3d1/Plugins/postgres.go:17 +0x1d4
reflect.Value.call(0xb44220, 0xcabde8, 0x13, 0xc56c6f, 0x4, 0xc00114a000, 0x1, 0x1, 0xc0009d4690, 0x44daec, ...)
        reflect/value.go:476 +0x8e7
reflect.Value.Call(0xb44220, 0xcabde8, 0x13, 0xc00114a000, 0x1, 0x1, 0xc0000380b0, 0x0, 0xb65d00)
        reflect/value.go:337 +0xb9
github.com/shadow1ng/fscan/Plugins.ScanFunc(0xc0003babd0, 0xc00089824c, 0x4, 0xc0009d4798, 0x1, 0x1, 0x4fc205, 0xd64b90, 0xc0000380b0, 0xd5c430, ...)
        github.com/shadow1ng/fscan@v0.0.0-20210529121601-162d1dd3a3d1/Plugins/scanner.go:107 +0x23a
github.com/shadow1ng/fscan/Plugins.AddScan.func1(0xc00089824c, 0x4, 0xc0000108c0, 0xc0003c7510, 0xc0000a28a0)
        github.com/shadow1ng/fscan@v0.0.0-20210529121601-162d1dd3a3d1/Plugins/scanner.go:86 +0xc5
created by github.com/shadow1ng/fscan/Plugins.AddScan
        github.com/shadow1ng/fscan@v0.0.0-20210529121601-162d1dd3a3d1/Plugins/scanner.go:82 +0xdd
```
![image](https://user-images.githubusercontent.com/51145610/125598584-c071eafe-3e24-4537-86f6-1d7a2dcf1c4a.png)

**Comment by niudaii** [comment]
https://www.modb.pro/db/144201
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/41844046/182083283-6ede9ae2-030d-49ac-82bd-e03986877988.png">

**Comment by shadow1ng** [comment]
可以先临时跳过pgsql扫描，-pn 5432

**Comment by niudaii** [comment]
https://www.modb.pro/db/144201
<img width="892" alt="image" src="https://user-images.githubusercontent.com/41844046/182083865-9beaa6c5-043e-47ff-8764-f58e56db1d92.png">

**Comment by shadow1ng** [comment]
那我更新一下go.mod就行

**Comment by shadow1ng** [comment]
师傅更新下go.mod 重新编译试试

**Comment by niudaii** [comment]
最新就是pq@v1.10.4，需要的话得改源码重新编译才行
go/pkg/mod/github.com/lib/pq@v1.10.4/conn.go:2007

**Comment by shadow1ng** [comment]
最新更新到1.10.6了

**Comment by shadow1ng** [comment]
![image](https://user-images.githubusercontent.com/39651966/182086476-2d85e141-0204-4c22-8ec3-03f1123d8cae.png)

**Comment by shadow1ng** [comment]
啊这，不过他这个1.10.6里的对应代码没改

**Comment by niudaii** [comment]
嗯嗯，那有需要的话还是改源码吧，参考那个链接自己重新编译就好了。
